---
apiVersion: v1
kind: Service
metadata:
  name: skf-flask-back
  labels:
    app.kubernetes.io/name: skf-flask-back
    app.kubernetes.io/instance: skf-flask-back
    app.kubernetes.io/version: "2.2.2"
spec:
  type: LoadBalancer
  ports:
    - port: 8888
  selector:
    app.kubernetes.io/name: skf-flask-back
    app.kubernetes.io/instance: skf-flask-back
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: skf-flask-back
  labels:
    app.kubernetes.io/name: skf-flask-back
    app.kubernetes.io/instance: skf-flask-back
    app.kubernetes.io/version: "2.2.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: skf-flask-back
      app.kubernetes.io/instance: skf-flask-back
  template:
    metadata:
      labels:
        app.kubernetes.io/name: skf-flask-back
        app.kubernetes.io/instance: skf-flask-back
    spec:
      containers:
        - name: skf-flask-back
          image: "docker.io/blabla1337/skf-flask:skf-api-demo"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8888
          env:
          -  name: ORIGIN
             valueFrom: 
               configMapKeyRef: 
                 name: skf-flask-back
                 key: ORIGIN
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: skf-flask-back
                key: JWT_SECRET
---